### ISSUE TITLE
Error: pls set RK_PARAMETER_TXT

### ISSUE THREAD

**Issue by wuweidong0107** [friendlyarm/sd-fuse_rk3568#1]
Found a error.

$ ./fusing.sh /dev/mmcblk0 out/rk3568-sd-friendlycore-lite-focal-5.10-arm64-20220612.img
Error: pls set RK_PARAMETER_TXT.

**Comment by friendlyarm** [comment]
This issue has been fixed, the below is the command example:
./fusing.sh /dev/sdX debian-buster-desktop-arm64
